Repository NUMde/compass-numapp-backend, pull requests merged in 2021-09, with the labels that each got.

#37 Added support to end participation in study
  db/migration/V001__Setup_Tables.sql
  src/assets/openapi.yaml
  src/controllers/ParticipantController.ts
  src/models/ExampleStateModel.ts
  src/models/ParticipantModel.ts
  src/types/ParticipantEntry.ts
Labels: enhancement

#50 Delete compass-backend-template-limit-range.yaml
  ocp_deployment/README.adoc
  ocp_deployment/templates/compass-backend-template-limit-range.yaml
Labels: clean up

#44 remove unused params in ocp deployment templates
  ocp_deployment/templates/compass-backend-template-prod.yaml
  ocp_deployment/templates/compass-backend-template.yaml
Labels: clean up

#53 Documentation enhancement
  ocp_deployment/README.adoc
Labels: documentation

#56 exclude 'google-services-secret.yaml' from git
  ocp_deployment/README.adoc
  ocp_deployment/templates/.gitignore
  ocp_deployment/templates/google-services-secret.yaml.sample
Labels: documentation, enhancement
